spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/project_be10_team1_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge203yXO)
  jpa:
    hibernate:
      ddl-auto: create