
//도서 등록
POST http://localhost:10304/admin/books
Content-Type: application/json

{
  "title": "이윤기의 그리스 로마 신화 1 - 신화를 이해하는 12가지 열쇠",
  "contents": "이 책에서 저자는 지리한 옛 이야기가 아닌 '인간 이해의 열쇠'로서 신화를 얘기한다. 책의 구성도 신들의 이야기를 죽 나열한 것이 아니라 하나의 주제를 잡아 여러 신화들을 자유롭게 넘나들며 그 속에 담겨 있는 상징성을 얘기한다. 주제는 사랑·나무·뱀·대홍수·술 등 12가지.",
  "description": "이 책에서 저자는 지리한 옛 이야기가 아닌 '인간 이해의 열쇠'로서 신화를 얘기한다. 책의 구성도 신들의 이야기를 죽 나열한 것이 아니라 하나의 주제를 잡아 여러 신화들을 자유롭게 넘나들며 그 속에 담겨 있는 상징성을 얘기한다. 주제는 사랑·나무·뱀·대홍수·술 등 12가지.",
  "author": "이윤기 (지은이)",
  "publisher": "웅진지식하우스",
  "pubDate": "2000-06-26",
  "isbn": "8901072394",
  "regularPrice": 13500,
  "salePrice": 12150,
  "cover": "https://image.aladin.co.kr/product/23/98/coversum/8901072394_2.jpg",
  "count": 0,
  "categoryId": 2
}
