### 책 추가
POST http://localhost:10304/admin/books
Content-Type: application/json

{
  "title": "모두의 자바",
  "contents": "기초 문법부터 객체지향까지",
  "description": "초보자를 위한 자바 입문서입니다.",
  "author": "홍길동",
  "publisher": "길벗",
  "pubDate": "2023-11-12",
  "isbn": "9781234567890",
  "regularPrice": 20000,
  "salePrice": 18000,
  "cover": "https://example.com/image.jpg",
  "count": 50,
  "categoryId": 8
}

### 등록도서 조회
GET http://localhost:10304/admin/books

### 카테고리 조회
GET http://localhost:10304/categories

### 카테고리 정보 조회 (ID기준)
GET http://localhost:10304/categories/8

### 리뷰작성 1
POST http://localhost:8080/books/1/reviews
Content-Type: application/json

{
  "reviewTitle": "책이 재미 없어요.",
  "reviewContent": "종이가 아깝습니다.",
  "reviewImageUrl": "/img/test.png",
  "reviewRating": 1
}

### 리뷰작성 2
POST http://localhost:8080/books/1/reviews
Content-Type: application/json

{
  "reviewTitle": "대충 호들갑 떠는 제목",
  "reviewContent": "대충 호들갑 떠는 내용",
  "reviewImageUrl": "/img/test.png",
  "reviewRating": 5
}

### 리뷰목록 조회
GET http://localhost:8080/books/1/reviews

### 리뷰상세 페이지
GET http://localhost:8080/books/1/reviews/1

### 리뷰 수정
PUT http://localhost:8080/books/1/reviews/2
Content-Type: application/json

{
  "reviewTitle": "ㅋㅋ",
  "reviewContent": "메롱",
  "reviewImageUrl": "",
  "reviewRating": 3
}

### 리뷰목록 조회
GET http://localhost:8080/books/1/reviews

### 리뷰 좋아요 설정
POST http://localhost:8080/books/1/reviews/1/like

### 리뷰 좋아요 상태 가져오기
GET http://localhost:8080/books/1/reviews/1/like

### 리뷰 좋아요 취소하기
DELETE http://localhost:8080/books/1/reviews/1/like

### 리뷰 좋아요 상태 가져오기
GET http://localhost:8080/books/1/reviews/1/like